version: "3.5"
services:
  server:
    image: test
    container_name: server
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mariadb
    container_name: database
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=root'
      - 'MARIADB_DB=moodle'